BOARD="MAX 10 DE10 - Lite"
OUT_DIR="output_files"              # quartus-prime defaults to output_files, but you can set it to whatever
TOP_LEVEL_ENTITY="example_entity"	# one of your VHDL files must have this entity defined in it
PERSISTENT_PROGRAMMING=false        # the board will remember the program after losing power if set to true