#! /usr/bin/env bash

#########################################################################################################################
#   ________  ___  ___  ________  ________  _________  ___  ___  ________                 ________  ___       ___     	#
#  |\   __  \|\  \|\  \|\   __  \|\   __  \|\___   ___\\  \|\  \|\   ____\               |\   ____\|\  \     |\  \    	#
#  \ \  \|\  \ \  \\\  \ \  \|\  \ \  \|\  \|___ \  \_\ \  \\\  \ \  \___|_  ____________\ \  \___|\ \  \    \ \  \   	#
#   \ \  \\\  \ \  \\\  \ \   __  \ \   _  _\   \ \  \ \ \  \\\  \ \_____  \|\____________\ \  \    \ \  \    \ \  \  	#
#    \ \  \\\  \ \  \\\  \ \  \ \  \ \  \\  \|   \ \  \ \ \  \\\  \|____|\  \|____________|\ \  \____\ \  \____\ \  \ 	#
#     \ \_____  \ \_______\ \__\ \__\ \__\\ _\    \ \__\ \ \_______\____\_\  \              \ \_______\ \_______\ \__\	#
#      \|___| \__\|_______|\|__|\|__|\|__|\|__|    \|__|  \|_______|\_________\              \|_______|\|_______|\|__|	#
#            \|__|                                                 \|_________|                                       	#
#																														#
#																														#
# Description:  																										#
#			A tool for building and flashing Intel FPGA designs from the command line!									#
#																														#
# Commands:																												#
#			build compiles the project into a binary that is ready to flash onto the board								#
#			flash programs the board with the compiled binary															#
#																														#
# Instructions:																											#
#			Make sure to have Quartus 25.1 installed on your system as well additional packages that may 				#
#			be needed to support your particular board. This file must be set as executable.							#
#			The project name as well as the default top-level entity name are inherited from this project 				#
#			directory. The script searches for any nested VHDL .vdh source files within the top-level 					#
#			directory, so feel free to organize them as you wish. However, you may still need to specify 				#
# 			the top-level entity name if it is not the same as the project's name. The top-level entity 				#
#			is defined in one of your VHDL	files and serves as the project's entrypoint. Configuration 				#
#			options can be written to quartus.conf and an example is provided in the repository.						#
# 																 														#
# General workflow:						 										 										#	
#		 	1. make the project directory																				#
# 			2. source the quartus.sh file in your shell	(make sure it is executable)									#
#			3. make your source files and declare at least the top-level entity											#
#			4. modify the config options to your needs either here or in quartus.conf									#
#			5. quartus-cli build																						#
#			6. quartus-cli flash																						#
# 																 														#
# Supported Boards:																										#
#			"MAX 10 DE10 - Lite"		 																				#
# 																 														#
# Author: 																												#
# 			Luca Jones																									#
#					 																									#
#########################################################################################################################
VERSION="25.1"
case "$(uname -s)" in
    Linux)   QUARTUS_BIN="/opt/intelFPGA/${VERSION}/quartus/bin" ;;
    MINGW*|MSYS*|CYGWIN*)  QUARTUS_BIN="/c/altera_lite/${VERSION}std/quartus/bin64" ;;
    *)       echo "Unsupported OS" >&2; exit 1 ;;
esac
export PATH="$PATH:$QUARTUS_BIN"

RED="\033[0;31m"
GREEN="\033[0;32m"
NC="\033[0m"

# TODO: add more supported boards

q-help() {
    cat <<EOF
quartus-cli $VERSION - Quartus Prime Lite CLI wrapper for FPGA development

Usage: quartus-cli [command] [options]

Commands:
build		Synthesize, fit, and assemble
flash		Program the FPGA board
init		Initializes a template project within the current directory


Options:
-v | --version 	Displays the version of Quartus being used
-h | --help 	Displays this help message 
-p 		Force persistent programming when used with the flash command
EOF
}

# loads options from config if it exists
q-config() {

	# defaults
	BOARD="MAX 10 DE10 - Lite"
	OUT_DIR="output_files"		 # quartus-prime defaults to output_files, but you can set it to whatever
	TOP_LEVEL_ENTITY=""		 	 # one of your VHDL files must have this entity defined in it
	PERSISTENT_PROGRAMMING=true  # the board will remember the program after losing power if set to true
	PROJECT_NAME="$(basename $(pwd))"

	# defaults are overridden if a config exists
	[ -f quartus.conf ] && eval "$(sed 's/ *= */=/' quartus.conf)"

	# define board-specific variables
	case "$BOARD" in
	"MAX 10 DE10 - Lite")
		FAMILY="MAX 10"
		DEVICE="10M50DAF484C6GES"
		;;
	"DE0-CV Development Board")
		FAMILY="Cyclone V"
		DEVICE="5CEBA4F23C7"
		;;
	*)
		echo "Unknown board: $BOARD"
		;;
	esac
}

# initializes quartus project files needed for building
q-generate-project-files() {

	{
		echo "PROJECT_REVISION = \"$PROJECT_NAME\""
	} > $PROJECT_NAME.qpf

	{
		if [ -n "$TOP_LEVEL_ENTITY" ]; then
			echo "set_global_assignment -name TOP_LEVEL_ENTITY \"${TOP_LEVEL_ENTITY}\""	
		fi
		echo "set_global_assignment -name FAMILY \"${FAMILY}\""
		echo "set_global_assignment -name DEVICE \"${DEVICE}\""
		echo "set_global_assignment -name BOARD \"${BOARD}\""
		echo "set_global_assignment -name PROJECT_OUTPUT_DIRECTORY ${OUT_DIR}"

		echo "set_global_assignment -name NUM_PARALLEL_PROCESSORS ALL"
		
		# board-specific settings
		case "$BOARD" in
		"MAX 10 DE10 - Lite")
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ADC_CLK_10"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to MAX10_CLK1_50"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to MAX10_CLK2_50"
			echo "set_location_assignment PIN_N5 -to ADC_CLK_10"
			echo "set_location_assignment PIN_P11 -to MAX10_CLK1_50"
			echo "set_location_assignment PIN_N14 -to MAX10_CLK2_50"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_BA[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_BA[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CAS_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CKE"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CLK"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CS_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[13]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[14]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[15]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_LDQM"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_RAS_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_UDQM"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_WE_N"
			echo "set_location_assignment PIN_U17 -to DRAM_ADDR[0]"
			echo "set_location_assignment PIN_W19 -to DRAM_ADDR[1]"
			echo "set_location_assignment PIN_V18 -to DRAM_ADDR[2]"
			echo "set_location_assignment PIN_U18 -to DRAM_ADDR[3]"
			echo "set_location_assignment PIN_U19 -to DRAM_ADDR[4]"
			echo "set_location_assignment PIN_T18 -to DRAM_ADDR[5]"
			echo "set_location_assignment PIN_T19 -to DRAM_ADDR[6]"
			echo "set_location_assignment PIN_R18 -to DRAM_ADDR[7]"
			echo "set_location_assignment PIN_P18 -to DRAM_ADDR[8]"
			echo "set_location_assignment PIN_P19 -to DRAM_ADDR[9]"
			echo "set_location_assignment PIN_T20 -to DRAM_ADDR[10]"
			echo "set_location_assignment PIN_P20 -to DRAM_ADDR[11]"
			echo "set_location_assignment PIN_R20 -to DRAM_ADDR[12]"
			echo "set_location_assignment PIN_T21 -to DRAM_BA[0]"
			echo "set_location_assignment PIN_T22 -to DRAM_BA[1]"
			echo "set_location_assignment PIN_U21 -to DRAM_CAS_N"
			echo "set_location_assignment PIN_N22 -to DRAM_CKE"
			echo "set_location_assignment PIN_L14 -to DRAM_CLK"
			echo "set_location_assignment PIN_U20 -to DRAM_CS_N"
			echo "set_location_assignment PIN_Y21 -to DRAM_DQ[0]"
			echo "set_location_assignment PIN_Y20 -to DRAM_DQ[1]"
			echo "set_location_assignment PIN_AA22 -to DRAM_DQ[2]"
			echo "set_location_assignment PIN_AA21 -to DRAM_DQ[3]"
			echo "set_location_assignment PIN_Y22 -to DRAM_DQ[4]"
			echo "set_location_assignment PIN_W22 -to DRAM_DQ[5]"
			echo "set_location_assignment PIN_W20 -to DRAM_DQ[6]"
			echo "set_location_assignment PIN_V21 -to DRAM_DQ[7]"
			echo "set_location_assignment PIN_P21 -to DRAM_DQ[8]"
			echo "set_location_assignment PIN_J22 -to DRAM_DQ[9]"
			echo "set_location_assignment PIN_H21 -to DRAM_DQ[10]"
			echo "set_location_assignment PIN_H22 -to DRAM_DQ[11]"
			echo "set_location_assignment PIN_G22 -to DRAM_DQ[12]"
			echo "set_location_assignment PIN_G20 -to DRAM_DQ[13]"
			echo "set_location_assignment PIN_G19 -to DRAM_DQ[14]"
			echo "set_location_assignment PIN_F22 -to DRAM_DQ[15]"
			echo "set_location_assignment PIN_V22 -to DRAM_LDQM"
			echo "set_location_assignment PIN_U22 -to DRAM_RAS_N"
			echo "set_location_assignment PIN_J21 -to DRAM_UDQM"
			echo "set_location_assignment PIN_V20 -to DRAM_WE_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[7]"
			echo "set_location_assignment PIN_C14 -to HEX0[0]"
			echo "set_location_assignment PIN_E15 -to HEX0[1]"
			echo "set_location_assignment PIN_C15 -to HEX0[2]"
			echo "set_location_assignment PIN_C16 -to HEX0[3]"
			echo "set_location_assignment PIN_E16 -to HEX0[4]"
			echo "set_location_assignment PIN_D17 -to HEX0[5]"
			echo "set_location_assignment PIN_C17 -to HEX0[6]"
			echo "set_location_assignment PIN_D15 -to HEX0[7]"
			echo "set_location_assignment PIN_C18 -to HEX1[0]"
			echo "set_location_assignment PIN_D18 -to HEX1[1]"
			echo "set_location_assignment PIN_E18 -to HEX1[2]"
			echo "set_location_assignment PIN_B16 -to HEX1[3]"
			echo "set_location_assignment PIN_A17 -to HEX1[4]"
			echo "set_location_assignment PIN_A18 -to HEX1[5]"
			echo "set_location_assignment PIN_B17 -to HEX1[6]"
			echo "set_location_assignment PIN_A16 -to HEX1[7]"
			echo "set_location_assignment PIN_B20 -to HEX2[0]"
			echo "set_location_assignment PIN_A20 -to HEX2[1]"
			echo "set_location_assignment PIN_B19 -to HEX2[2]"
			echo "set_location_assignment PIN_A21 -to HEX2[3]"
			echo "set_location_assignment PIN_B21 -to HEX2[4]"
			echo "set_location_assignment PIN_C22 -to HEX2[5]"
			echo "set_location_assignment PIN_B22 -to HEX2[6]"
			echo "set_location_assignment PIN_A19 -to HEX2[7]"
			echo "set_location_assignment PIN_F21 -to HEX3[0]"
			echo "set_location_assignment PIN_E22 -to HEX3[1]"
			echo "set_location_assignment PIN_E21 -to HEX3[2]"
			echo "set_location_assignment PIN_C19 -to HEX3[3]"
			echo "set_location_assignment PIN_C20 -to HEX3[4]"
			echo "set_location_assignment PIN_D19 -to HEX3[5]"
			echo "set_location_assignment PIN_E17 -to HEX3[6]"
			echo "set_location_assignment PIN_D22 -to HEX3[7]"
			echo "set_location_assignment PIN_F18 -to HEX4[0]"
			echo "set_location_assignment PIN_E20 -to HEX4[1]"
			echo "set_location_assignment PIN_E19 -to HEX4[2]"
			echo "set_location_assignment PIN_J18 -to HEX4[3]"
			echo "set_location_assignment PIN_H19 -to HEX4[4]"
			echo "set_location_assignment PIN_F19 -to HEX4[5]"
			echo "set_location_assignment PIN_F20 -to HEX4[6]"
			echo "set_location_assignment PIN_F17 -to HEX4[7]"
			echo "set_location_assignment PIN_J20 -to HEX5[0]"
			echo "set_location_assignment PIN_K20 -to HEX5[1]"
			echo "set_location_assignment PIN_L18 -to HEX5[2]"
			echo "set_location_assignment PIN_N18 -to HEX5[3]"
			echo "set_location_assignment PIN_M20 -to HEX5[4]"
			echo "set_location_assignment PIN_N19 -to HEX5[5]"
			echo "set_location_assignment PIN_N20 -to HEX5[6]"
			echo "set_location_assignment PIN_L19 -to HEX5[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3 V SCHMITT TRIGGER\" -to KEY[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3 V SCHMITT TRIGGER\" -to KEY[1]"
			echo "set_location_assignment PIN_B8 -to KEY[0]"
			echo "set_location_assignment PIN_A7 -to KEY[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[9]"
			echo "set_location_assignment PIN_A8 -to LEDR[0]"
			echo "set_location_assignment PIN_A9 -to LEDR[1]"
			echo "set_location_assignment PIN_A10 -to LEDR[2]"
			echo "set_location_assignment PIN_B10 -to LEDR[3]"
			echo "set_location_assignment PIN_D13 -to LEDR[4]"
			echo "set_location_assignment PIN_C13 -to LEDR[5]"
			echo "set_location_assignment PIN_E14 -to LEDR[6]"
			echo "set_location_assignment PIN_D14 -to LEDR[7]"
			echo "set_location_assignment PIN_A11 -to LEDR[8]"
			echo "set_location_assignment PIN_B11 -to LEDR[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[9]"
			echo "set_location_assignment PIN_C10 -to SW[0]"
			echo "set_location_assignment PIN_C11 -to SW[1]"
			echo "set_location_assignment PIN_D12 -to SW[2]"
			echo "set_location_assignment PIN_C12 -to SW[3]"
			echo "set_location_assignment PIN_A12 -to SW[4]"
			echo "set_location_assignment PIN_B12 -to SW[5]"
			echo "set_location_assignment PIN_A13 -to SW[6]"
			echo "set_location_assignment PIN_A14 -to SW[7]"
			echo "set_location_assignment PIN_B14 -to SW[8]"
			echo "set_location_assignment PIN_F15 -to SW[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_HS"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_VS"
			echo "set_location_assignment PIN_P1 -to VGA_B[0]"
			echo "set_location_assignment PIN_T1 -to VGA_B[1]"
			echo "set_location_assignment PIN_P4 -to VGA_B[2]"
			echo "set_location_assignment PIN_N2 -to VGA_B[3]"
			echo "set_location_assignment PIN_W1 -to VGA_G[0]"
			echo "set_location_assignment PIN_T2 -to VGA_G[1]"
			echo "set_location_assignment PIN_R2 -to VGA_G[2]"
			echo "set_location_assignment PIN_R1 -to VGA_G[3]"
			echo "set_location_assignment PIN_N3 -to VGA_HS"
			echo "set_location_assignment PIN_AA1 -to VGA_R[0]"
			echo "set_location_assignment PIN_V1 -to VGA_R[1]"
			echo "set_location_assignment PIN_Y2 -to VGA_R[2]"
			echo "set_location_assignment PIN_Y1 -to VGA_R[3]"
			echo "set_location_assignment PIN_N1 -to VGA_VS"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GSENSOR_CS_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GSENSOR_INT[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GSENSOR_INT[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GSENSOR_SCLK"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GSENSOR_SDI"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GSENSOR_SDO"
			echo "set_location_assignment PIN_AB16 -to GSENSOR_CS_N"
			echo "set_location_assignment PIN_Y14 -to GSENSOR_INT[1]"
			echo "set_location_assignment PIN_Y13 -to GSENSOR_INT[2]"
			echo "set_location_assignment PIN_AB15 -to GSENSOR_SCLK"
			echo "set_location_assignment PIN_V11 -to GSENSOR_SDI"
			echo "set_location_assignment PIN_V12 -to GSENSOR_SDO"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[13]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[14]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_IO[15]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to ARDUINO_RESET_N"
			echo "set_location_assignment PIN_AB5 -to ARDUINO_IO[0]"
			echo "set_location_assignment PIN_AB6 -to ARDUINO_IO[1]"
			echo "set_location_assignment PIN_AB7 -to ARDUINO_IO[2]"
			echo "set_location_assignment PIN_AB8 -to ARDUINO_IO[3]"
			echo "set_location_assignment PIN_AB9 -to ARDUINO_IO[4]"
			echo "set_location_assignment PIN_Y10 -to ARDUINO_IO[5]"
			echo "set_location_assignment PIN_AA11 -to ARDUINO_IO[6]"
			echo "set_location_assignment PIN_AA12 -to ARDUINO_IO[7]"
			echo "set_location_assignment PIN_AB17 -to ARDUINO_IO[8]"
			echo "set_location_assignment PIN_AA17 -to ARDUINO_IO[9]"
			echo "set_location_assignment PIN_AB19 -to ARDUINO_IO[10]"
			echo "set_location_assignment PIN_AA19 -to ARDUINO_IO[11]"
			echo "set_location_assignment PIN_Y19 -to ARDUINO_IO[12]"
			echo "set_location_assignment PIN_AB20 -to ARDUINO_IO[13]"
			echo "set_location_assignment PIN_AB21 -to ARDUINO_IO[14]"
			echo "set_location_assignment PIN_AA20 -to ARDUINO_IO[15]"
			echo "set_location_assignment PIN_F16 -to ARDUINO_RESET_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[13]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[14]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[15]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[16]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[17]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[18]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[19]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[20]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[21]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[22]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[23]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[24]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[25]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[26]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[27]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[28]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[29]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[30]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[31]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[32]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[33]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[34]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO[35]"
			echo "set_location_assignment PIN_V10 -to GPIO[0]"
			echo "set_location_assignment PIN_W10 -to GPIO[1]"
			echo "set_location_assignment PIN_V9 -to GPIO[2]"
			echo "set_location_assignment PIN_W9 -to GPIO[3]"
			echo "set_location_assignment PIN_V8 -to GPIO[4]"
			echo "set_location_assignment PIN_W8 -to GPIO[5]"
			echo "set_location_assignment PIN_V7 -to GPIO[6]"
			echo "set_location_assignment PIN_W7 -to GPIO[7]"
			echo "set_location_assignment PIN_W6 -to GPIO[8]"
			echo "set_location_assignment PIN_V5 -to GPIO[9]"
			echo "set_location_assignment PIN_W5 -to GPIO[10]"
			echo "set_location_assignment PIN_AA15 -to GPIO[11]"
			echo "set_location_assignment PIN_AA14 -to GPIO[12]"
			echo "set_location_assignment PIN_W13 -to GPIO[13]"
			echo "set_location_assignment PIN_W12 -to GPIO[14]"
			echo "set_location_assignment PIN_AB13 -to GPIO[15]"
			echo "set_location_assignment PIN_AB12 -to GPIO[16]"
			echo "set_location_assignment PIN_Y11 -to GPIO[17]"
			echo "set_location_assignment PIN_AB11 -to GPIO[18]"
			echo "set_location_assignment PIN_W11 -to GPIO[19]"
			echo "set_location_assignment PIN_AB10 -to GPIO[20]"
			echo "set_location_assignment PIN_AA10 -to GPIO[21]"
			echo "set_location_assignment PIN_AA9 -to GPIO[22]"
			echo "set_location_assignment PIN_Y8 -to GPIO[23]"
			echo "set_location_assignment PIN_AA8 -to GPIO[24]"
			echo "set_location_assignment PIN_Y7 -to GPIO[25]"
			echo "set_location_assignment PIN_AA7 -to GPIO[26]"
			echo "set_location_assignment PIN_Y6 -to GPIO[27]"
			echo "set_location_assignment PIN_AA6 -to GPIO[28]"
			echo "set_location_assignment PIN_Y5 -to GPIO[29]"
			echo "set_location_assignment PIN_AA5 -to GPIO[30]"
			echo "set_location_assignment PIN_Y4 -to GPIO[31]"
			echo "set_location_assignment PIN_AB3 -to GPIO[32]"
			echo "set_location_assignment PIN_Y3 -to GPIO[33]"
			echo "set_location_assignment PIN_AB2 -to GPIO[34]"
			echo "set_location_assignment PIN_AA2 -to GPIO[35]"
			;;
		"DE0-CV Development Board")
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to CLOCK2_50"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to CLOCK3_50"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to CLOCK4_50"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to CLOCK_50"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_ADDR[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_BA[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_BA[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CAS_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CKE"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CLK"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_CS_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[13]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[14]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_DQ[15]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_LDQM"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_RAS_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_UDQM"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to DRAM_WE_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[13]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[14]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[15]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[16]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[17]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[18]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[19]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[20]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[21]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[22]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[23]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[24]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[25]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[26]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[27]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[28]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[29]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[30]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[31]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[32]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[33]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[34]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_0[35]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[10]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[11]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[12]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[13]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[14]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[15]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[16]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[17]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[18]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[19]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[20]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[21]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[22]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[23]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[24]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[25]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[26]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[27]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[28]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[29]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[30]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[31]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[32]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[33]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[34]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to GPIO_1[35]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX0[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX1[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX2[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX3[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX4[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to HEX5[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to KEY[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to KEY[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to KEY[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to KEY[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to LEDR[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to PS2_CLK"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to PS2_CLK2"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to PS2_DAT"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to PS2_DAT2"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to RESET_N"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SD_CLK"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SD_CMD"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SD_DATA[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SD_DATA[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SD_DATA[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SD_DATA[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[4]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[5]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[6]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[7]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[8]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to SW[9]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_B[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_G[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_HS"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[0]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[1]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[2]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_R[3]"
			echo "set_instance_assignment -name IO_STANDARD \"3.3-V LVTTL\" -to VGA_VS"
			echo "set_location_assignment PIN_H13 -to CLOCK2_50"
			echo "set_location_assignment PIN_E10 -to CLOCK3_50"
			echo "set_location_assignment PIN_V15 -to CLOCK4_50"
			echo "set_location_assignment PIN_M9 -to CLOCK_50"
			echo "set_location_assignment PIN_W8 -to DRAM_ADDR[0]"
			echo "set_location_assignment PIN_T8 -to DRAM_ADDR[1]"
			echo "set_location_assignment PIN_U11 -to DRAM_ADDR[2]"
			echo "set_location_assignment PIN_Y10 -to DRAM_ADDR[3]"
			echo "set_location_assignment PIN_N6 -to DRAM_ADDR[4]"
			echo "set_location_assignment PIN_AB10 -to DRAM_ADDR[5]"
			echo "set_location_assignment PIN_P12 -to DRAM_ADDR[6]"
			echo "set_location_assignment PIN_P7 -to DRAM_ADDR[7]"
			echo "set_location_assignment PIN_P8 -to DRAM_ADDR[8]"
			echo "set_location_assignment PIN_R5 -to DRAM_ADDR[9]"
			echo "set_location_assignment PIN_U8 -to DRAM_ADDR[10]"
			echo "set_location_assignment PIN_P6 -to DRAM_ADDR[11]"
			echo "set_location_assignment PIN_R7 -to DRAM_ADDR[12]"
			echo "set_location_assignment PIN_T7 -to DRAM_BA[0]"
			echo "set_location_assignment PIN_AB7 -to DRAM_BA[1]"
			echo "set_location_assignment PIN_V6 -to DRAM_CAS_N"
			echo "set_location_assignment PIN_R6 -to DRAM_CKE"
			echo "set_location_assignment PIN_AB11 -to DRAM_CLK"
			echo "set_location_assignment PIN_U6 -to DRAM_CS_N"
			echo "set_location_assignment PIN_Y9 -to DRAM_DQ[0]"
			echo "set_location_assignment PIN_T10 -to DRAM_DQ[1]"
			echo "set_location_assignment PIN_R9 -to DRAM_DQ[2]"
			echo "set_location_assignment PIN_Y11 -to DRAM_DQ[3]"
			echo "set_location_assignment PIN_R10 -to DRAM_DQ[4]"
			echo "set_location_assignment PIN_R11 -to DRAM_DQ[5]"
			echo "set_location_assignment PIN_R12 -to DRAM_DQ[6]"
			echo "set_location_assignment PIN_AA12 -to DRAM_DQ[7]"
			echo "set_location_assignment PIN_AA9 -to DRAM_DQ[8]"
			echo "set_location_assignment PIN_AB8 -to DRAM_DQ[9]"
			echo "set_location_assignment PIN_AA8 -to DRAM_DQ[10]"
			echo "set_location_assignment PIN_AA7 -to DRAM_DQ[11]"
			echo "set_location_assignment PIN_V10 -to DRAM_DQ[12]"
			echo "set_location_assignment PIN_V9 -to DRAM_DQ[13]"
			echo "set_location_assignment PIN_U10 -to DRAM_DQ[14]"
			echo "set_location_assignment PIN_T9 -to DRAM_DQ[15]"
			echo "set_location_assignment PIN_U12 -to DRAM_LDQM"
			echo "set_location_assignment PIN_AB6 -to DRAM_RAS_N"
			echo "set_location_assignment PIN_N8 -to DRAM_UDQM"
			echo "set_location_assignment PIN_AB5 -to DRAM_WE_N"
			echo "set_location_assignment PIN_N16 -to GPIO_0[0]"
			echo "set_location_assignment PIN_B16 -to GPIO_0[1]"
			echo "set_location_assignment PIN_M16 -to GPIO_0[2]"
			echo "set_location_assignment PIN_C16 -to GPIO_0[3]"
			echo "set_location_assignment PIN_D17 -to GPIO_0[4]"
			echo "set_location_assignment PIN_K20 -to GPIO_0[5]"
			echo "set_location_assignment PIN_K21 -to GPIO_0[6]"
			echo "set_location_assignment PIN_K22 -to GPIO_0[7]"
			echo "set_location_assignment PIN_M20 -to GPIO_0[8]"
			echo "set_location_assignment PIN_M21 -to GPIO_0[9]"
			echo "set_location_assignment PIN_N21 -to GPIO_0[10]"
			echo "set_location_assignment PIN_R22 -to GPIO_0[11]"
			echo "set_location_assignment PIN_R21 -to GPIO_0[12]"
			echo "set_location_assignment PIN_T22 -to GPIO_0[13]"
			echo "set_location_assignment PIN_N20 -to GPIO_0[14]"
			echo "set_location_assignment PIN_N19 -to GPIO_0[15]"
			echo "set_location_assignment PIN_M22 -to GPIO_0[16]"
			echo "set_location_assignment PIN_P19 -to GPIO_0[17]"
			echo "set_location_assignment PIN_L22 -to GPIO_0[18]"
			echo "set_location_assignment PIN_P17 -to GPIO_0[19]"
			echo "set_location_assignment PIN_P16 -to GPIO_0[20]"
			echo "set_location_assignment PIN_M18 -to GPIO_0[21]"
			echo "set_location_assignment PIN_L18 -to GPIO_0[22]"
			echo "set_location_assignment PIN_L17 -to GPIO_0[23]"
			echo "set_location_assignment PIN_L19 -to GPIO_0[24]"
			echo "set_location_assignment PIN_K17 -to GPIO_0[25]"
			echo "set_location_assignment PIN_K19 -to GPIO_0[26]"
			echo "set_location_assignment PIN_P18 -to GPIO_0[27]"
			echo "set_location_assignment PIN_R15 -to GPIO_0[28]"
			echo "set_location_assignment PIN_R17 -to GPIO_0[29]"
			echo "set_location_assignment PIN_R16 -to GPIO_0[30]"
			echo "set_location_assignment PIN_T20 -to GPIO_0[31]"
			echo "set_location_assignment PIN_T19 -to GPIO_0[32]"
			echo "set_location_assignment PIN_T18 -to GPIO_0[33]"
			echo "set_location_assignment PIN_T17 -to GPIO_0[34]"
			echo "set_location_assignment PIN_T15 -to GPIO_0[35]"
			echo "set_location_assignment PIN_H16 -to GPIO_1[0]"
			echo "set_location_assignment PIN_A12 -to GPIO_1[1]"
			echo "set_location_assignment PIN_H15 -to GPIO_1[2]"
			echo "set_location_assignment PIN_B12 -to GPIO_1[3]"
			echo "set_location_assignment PIN_A13 -to GPIO_1[4]"
			echo "set_location_assignment PIN_B13 -to GPIO_1[5]"
			echo "set_location_assignment PIN_C13 -to GPIO_1[6]"
			echo "set_location_assignment PIN_D13 -to GPIO_1[7]"
			echo "set_location_assignment PIN_G18 -to GPIO_1[8]"
			echo "set_location_assignment PIN_G17 -to GPIO_1[9]"
			echo "set_location_assignment PIN_H18 -to GPIO_1[10]"
			echo "set_location_assignment PIN_J18 -to GPIO_1[11]"
			echo "set_location_assignment PIN_J19 -to GPIO_1[12]"
			echo "set_location_assignment PIN_G11 -to GPIO_1[13]"
			echo "set_location_assignment PIN_H10 -to GPIO_1[14]"
			echo "set_location_assignment PIN_J11 -to GPIO_1[15]"
			echo "set_location_assignment PIN_H14 -to GPIO_1[16]"
			echo "set_location_assignment PIN_A15 -to GPIO_1[17]"
			echo "set_location_assignment PIN_J13 -to GPIO_1[18]"
			echo "set_location_assignment PIN_L8 -to GPIO_1[19]"
			echo "set_location_assignment PIN_A14 -to GPIO_1[20]"
			echo "set_location_assignment PIN_B15 -to GPIO_1[21]"
			echo "set_location_assignment PIN_C15 -to GPIO_1[22]"
			echo "set_location_assignment PIN_E14 -to GPIO_1[23]"
			echo "set_location_assignment PIN_E15 -to GPIO_1[24]"
			echo "set_location_assignment PIN_E16 -to GPIO_1[25]"
			echo "set_location_assignment PIN_F14 -to GPIO_1[26]"
			echo "set_location_assignment PIN_F15 -to GPIO_1[27]"
			echo "set_location_assignment PIN_F13 -to GPIO_1[28]"
			echo "set_location_assignment PIN_F12 -to GPIO_1[29]"
			echo "set_location_assignment PIN_G16 -to GPIO_1[30]"
			echo "set_location_assignment PIN_G15 -to GPIO_1[31]"
			echo "set_location_assignment PIN_G13 -to GPIO_1[32]"
			echo "set_location_assignment PIN_G12 -to GPIO_1[33]"
			echo "set_location_assignment PIN_J17 -to GPIO_1[34]"
			echo "set_location_assignment PIN_K16 -to GPIO_1[35]"
			echo "set_location_assignment PIN_U21 -to HEX0[0]"
			echo "set_location_assignment PIN_V21 -to HEX0[1]"
			echo "set_location_assignment PIN_W22 -to HEX0[2]"
			echo "set_location_assignment PIN_W21 -to HEX0[3]"
			echo "set_location_assignment PIN_Y22 -to HEX0[4]"
			echo "set_location_assignment PIN_Y21 -to HEX0[5]"
			echo "set_location_assignment PIN_AA22 -to HEX0[6]"
			echo "set_location_assignment PIN_AA20 -to HEX1[0]"
			echo "set_location_assignment PIN_AB20 -to HEX1[1]"
			echo "set_location_assignment PIN_AA19 -to HEX1[2]"
			echo "set_location_assignment PIN_AA18 -to HEX1[3]"
			echo "set_location_assignment PIN_AB18 -to HEX1[4]"
			echo "set_location_assignment PIN_AA17 -to HEX1[5]"
			echo "set_location_assignment PIN_U22 -to HEX1[6]"
			echo "set_location_assignment PIN_Y19 -to HEX2[0]"
			echo "set_location_assignment PIN_AB17 -to HEX2[1]"
			echo "set_location_assignment PIN_AA10 -to HEX2[2]"
			echo "set_location_assignment PIN_Y14 -to HEX2[3]"
			echo "set_location_assignment PIN_V14 -to HEX2[4]"
			echo "set_location_assignment PIN_AB22 -to HEX2[5]"
			echo "set_location_assignment PIN_AB21 -to HEX2[6]"
			echo "set_location_assignment PIN_Y16 -to HEX3[0]"
			echo "set_location_assignment PIN_W16 -to HEX3[1]"
			echo "set_location_assignment PIN_Y17 -to HEX3[2]"
			echo "set_location_assignment PIN_V16 -to HEX3[3]"
			echo "set_location_assignment PIN_U17 -to HEX3[4]"
			echo "set_location_assignment PIN_V18 -to HEX3[5]"
			echo "set_location_assignment PIN_V19 -to HEX3[6]"
			echo "set_location_assignment PIN_U20 -to HEX4[0]"
			echo "set_location_assignment PIN_Y20 -to HEX4[1]"
			echo "set_location_assignment PIN_V20 -to HEX4[2]"
			echo "set_location_assignment PIN_U16 -to HEX4[3]"
			echo "set_location_assignment PIN_U15 -to HEX4[4]"
			echo "set_location_assignment PIN_Y15 -to HEX4[5]"
			echo "set_location_assignment PIN_P9 -to HEX4[6]"
			echo "set_location_assignment PIN_N9 -to HEX5[0]"
			echo "set_location_assignment PIN_M8 -to HEX5[1]"
			echo "set_location_assignment PIN_T14 -to HEX5[2]"
			echo "set_location_assignment PIN_P14 -to HEX5[3]"
			echo "set_location_assignment PIN_C1 -to HEX5[4]"
			echo "set_location_assignment PIN_C2 -to HEX5[5]"
			echo "set_location_assignment PIN_W19 -to HEX5[6]"
			echo "set_location_assignment PIN_U7 -to KEY[0]"
			echo "set_location_assignment PIN_W9 -to KEY[1]"
			echo "set_location_assignment PIN_M7 -to KEY[2]"
			echo "set_location_assignment PIN_M6 -to KEY[3]"
			echo "set_location_assignment PIN_AA2 -to LEDR[0]"
			echo "set_location_assignment PIN_AA1 -to LEDR[1]"
			echo "set_location_assignment PIN_W2 -to LEDR[2]"
			echo "set_location_assignment PIN_Y3 -to LEDR[3]"
			echo "set_location_assignment PIN_N2 -to LEDR[4]"
			echo "set_location_assignment PIN_N1 -to LEDR[5]"
			echo "set_location_assignment PIN_U2 -to LEDR[6]"
			echo "set_location_assignment PIN_U1 -to LEDR[7]"
			echo "set_location_assignment PIN_L2 -to LEDR[8]"
			echo "set_location_assignment PIN_L1 -to LEDR[9]"
			echo "set_location_assignment PIN_D3 -to PS2_CLK"
			echo "set_location_assignment PIN_E2 -to PS2_CLK2"
			echo "set_location_assignment PIN_G2 -to PS2_DAT"
			echo "set_location_assignment PIN_G1 -to PS2_DAT2"
			echo "set_location_assignment PIN_P22 -to RESET_N"
			echo "set_location_assignment PIN_H11 -to SD_CLK"
			echo "set_location_assignment PIN_B11 -to SD_CMD"
			echo "set_location_assignment PIN_K9 -to SD_DATA[0]"
			echo "set_location_assignment PIN_D12 -to SD_DATA[1]"
			echo "set_location_assignment PIN_E12 -to SD_DATA[2]"
			echo "set_location_assignment PIN_C11 -to SD_DATA[3]"
			echo "set_location_assignment PIN_U13 -to SW[0]"
			echo "set_location_assignment PIN_V13 -to SW[1]"
			echo "set_location_assignment PIN_T13 -to SW[2]"
			echo "set_location_assignment PIN_T12 -to SW[3]"
			echo "set_location_assignment PIN_AA15 -to SW[4]"
			echo "set_location_assignment PIN_AB15 -to SW[5]"
			echo "set_location_assignment PIN_AA14 -to SW[6]"
			echo "set_location_assignment PIN_AA13 -to SW[7]"
			echo "set_location_assignment PIN_AB13 -to SW[8]"
			echo "set_location_assignment PIN_AB12 -to SW[9]"
			echo "set_location_assignment PIN_B6 -to VGA_B[0]"
			echo "set_location_assignment PIN_B7 -to VGA_B[1]"
			echo "set_location_assignment PIN_A8 -to VGA_B[2]"
			echo "set_location_assignment PIN_A7 -to VGA_B[3]"
			echo "set_location_assignment PIN_L7 -to VGA_G[0]"
			echo "set_location_assignment PIN_K7 -to VGA_G[1]"
			echo "set_location_assignment PIN_J7 -to VGA_G[2]"
			echo "set_location_assignment PIN_J8 -to VGA_G[3]"
			echo "set_location_assignment PIN_H8 -to VGA_HS"
			echo "set_location_assignment PIN_A9 -to VGA_R[0]"
			echo "set_location_assignment PIN_B10 -to VGA_R[1]"
			echo "set_location_assignment PIN_C9 -to VGA_R[2]"
			echo "set_location_assignment PIN_A5 -to VGA_R[3]"
			echo "set_location_assignment PIN_G8 -to VGA_VS"
			echo "set_global_assignment -name CYCLONEII_RESERVE_NCEO_AFTER_CONFIGURATION \"USE AS REGULAR IO\""
			echo "set_global_assignment -name PARTITION_NETLIST_TYPE SOURCE -section_id Top"
			echo "set_global_assignment -name PARTITION_FITTER_PRESERVATION_LEVEL PLACEMENT_AND_ROUTING -section_id Top"
			echo "set_global_assignment -name PARTITION_COLOR 16764057 -section_id Top"
			echo "set_global_assignment -name STRATIX_DEVICE_IO_STANDARD \"2.5 V\""
			echo "set_global_assignment -name VERILOG_FILE DE0_CV_golden_top.v"
			echo "set_global_assignment -name OPTIMIZATION_TECHNIQUE SPEED"
			echo "set_global_assignment -name SYNTH_TIMING_DRIVEN_SYNTHESIS ON"
			echo "set_global_assignment -name OPTIMIZE_HOLD_TIMING \"ALL PATHS\""
			echo "set_global_assignment -name OPTIMIZE_MULTI_CORNER_TIMING ON"
			echo "set_global_assignment -name FITTER_EFFORT \"STANDARD FIT\""
			echo "set_global_assignment -name STRATIXV_CONFIGURATION_SCHEME \"ACTIVE SERIAL X1\""
			echo "set_global_assignment -name USE_CONFIGURATION_DEVICE ON"
			echo "set_global_assignment -name STRATIXII_CONFIGURATION_DEVICE EPCS64"
			echo "set_global_assignment -name CRC_ERROR_OPEN_DRAIN ON"
			echo "set_global_assignment -name OUTPUT_IO_TIMING_NEAR_END_VMEAS \"HALF VCCIO\" -rise"
			echo "set_global_assignment -name OUTPUT_IO_TIMING_NEAR_END_VMEAS \"HALF VCCIO\" -fall"
			echo "set_global_assignment -name OUTPUT_IO_TIMING_FAR_END_VMEAS \"HALF SIGNAL SWING\" -rise"
			echo "set_global_assignment -name OUTPUT_IO_TIMING_FAR_END_VMEAS \"HALF SIGNAL SWING\" -fall"
			echo "set_global_assignment -name ACTIVE_SERIAL_CLOCK FREQ_100MHZ"
			echo "set_instance_assignment -name PARTITION_HIERARCHY root_partition -to | -section_id Top"
			;;
		*)
			echo "Error: $BOARD board not supported" >&2
    		return 1
			;;
		esac

		# VHDL source files
		find . -name "*.vhd" | while read f; do
			echo "set_global_assignment -name VHDL_FILE ${f#./}"
		done

	} > $PROJECT_NAME.qsf

}

# generates a template project within the current directory
q-init() { 

	{
		echo "BOARD=\"MAX 10 DE10 - Lite\""
		echo "OUT_DIR=\"output_files\""  
		echo "TOP_LEVEL_ENTITY=\"$(basename $(pwd))\""
		echo "PERSISTENT_PROGRAMMING=false"
	} > quartus.conf

	{
		echo "library ieee;"
		echo "use ieee.std_logic_1164.all;"
		printf "\n"
		echo "entity $(basename $(pwd)) is"
		printf "\tport(\n"
		printf "\t\tSW   : in  std_logic_vector(9 downto 0);\n"
		printf "\t\tLEDR : out std_logic_vector(9 downto 0)\n"
		printf "\t);\n"
		echo "end entity;"
		printf "\n"
		echo "architecture behavior of $(basename $(pwd)) is"
		echo "begin"
		printf "\tLEDR <= SW;\n"
		echo "end architecture;"
	} > $(basename $(pwd)).vhd
}

spin() {
	local pid=$1
	local chars='|/-\'
	local i=0
	printf "  "
	while kill -0 "$pid" 2>/dev/null; do
		printf "\b%s" "${chars:$((i%4)):1}"
		i=$((i+1))
		sleep 0.1
	done
	printf "\b"
}

# compiles the fpga project and generates the OUT_DIR, db, and incremental_db directories
q-build() {
	set +m
	local start
	local log=$(mktemp)
	printf "%-35s" "[1/3] Synthesizing netlist"
	start=$SECONDS
	quartus_map $PROJECT_NAME --write_settings_files=off > "$log" 2>&1 &
	spin $!
	wait $!
	if [ $? -ne 0 ]; then
		printf "${RED}FAILED${NC}\n\n"
		grep -E "^\s*(Error|Warning)" "$log"
		# if [ -f "$OUT_DIR/${PROJECT_NAME}.map.rpt" ]; then
		# 	grep -E "^(Error|Warning)" "$OUT_DIR/${PROJECT_NAME}.map.rpt"
		# fi
		set -m
		return 1
	fi
	printf "${GREEN}DONE${NC} (%ds)\n" "$((SECONDS - start))"

	printf "%-35s" "[2/3] Fitting netlist to resources"
	start=$SECONDS
	quartus_fit $PROJECT_NAME > /dev/null 2>&1 &
	spin $!
	wait $!
	printf "${GREEN}DONE${NC} (%ds)\n" "$((SECONDS - start))"

	printf "%-35s" "[3/3] Assembling binaries"
	start=$SECONDS
	quartus_asm $PROJECT_NAME > /dev/null 2>&1 &
	spin $!
	wait $!
	printf "${GREEN}DONE${NC} (%ds)\n" "$((SECONDS - start))"

}

# run this after q-build to program the board
q-flash() {
	set +m
	local start=$SECONDS
	local log=$(mktemp)
	if $PERSISTENT_PROGRAMMING ; then
		printf "%-35s" "Flashing (Persistent)"
		quartus_pgm -m jtag -o "p;${OUT_DIR}/${PROJECT_NAME}.pof" > "$log" 2>&1 &
	else
		printf "%-35s" "Flashing (Not Persistent)"
		quartus_pgm -m jtag -o "p;${OUT_DIR}/${PROJECT_NAME}.sof" > "$log" 2>&1 &
	fi
	spin $!
	wait $!
	if [ $? -ne 0 ]; then
		printf "${RED}FAILED${NC}\n\n"
		grep -E "^\s*Error" "$log"
	else 
		printf "${GREEN}DONE${NC} (%ds)\n" "$((SECONDS - start))"
	fi
	set -m
}

case "$1" in
    build)
		q-config
		q-generate-project-files
        q-build
        ;;
    flash)
		q-config
		case "$2" in 
			-p)
				PERSISTENT_PROGRAMMING=true
				;;
			*)
				;;
		esac
        q-flash
        ;;
	init)
		q-init
		q-config
		q-generate-project-files
		;;
    -v | --version)
        echo "Quartus $VERSION"
        ;;
    -h | --help | "")
        q-help
        ;;
    *)
        echo "quartus-cli: unknown command '$1'" >&2
        echo "Run 'quartus-cli --help' for usage." >&2
        exit 1
        ;;
esac
